[workspace]
pre-release-hook = ["git", "cliff", "--output", "CHANGELOG.md", "--tag", "{{version}}"]
pre-release-commit-message = "chore(release): {{version}}"
tag-message = "Herald v{{version}}"
tag-prefix = "v"
sign-commit = true
sign-tag = true
publish = false
