//! TSIG key loading for RFC 2845/8945 authentication.
//!
//! Shared by the RFC 2136 backend (outbound signing), the DNS UPDATE receiver
//! (inbound verification), and the AXFR mirror source (query signing).
//!
//! # hickory-dns 0.26 API notes
//!
//! - **Signer attachment**: `DnsMultiplexer::with_signer(tsigner)` on the
//!   stream before constructing `Client::from_sender(multiplexer)`. The
//!   multiplexer auto-signs messages matching `TSigner::should_sign_message`
//!   (UPDATE, NOTIFY, AXFR/IXFR queries).
//! - **AXFR verification**: `DnsMultiplexer` holds a `TSigVerifier` that
//!   auto-verifies each response in the multi-message AXFR chain.

use anyhow::{Context, Result};
use base64::Engine as _;
use base64::engine::general_purpose::STANDARD as BASE64;
use hickory_proto::rr::rdata::tsig::TsigAlgorithm;
use hickory_proto::rr::{Name, TSigner};

/// Default TSIG fudge: permitted clock skew in seconds.
pub(crate) const TSIG_FUDGE: u16 = 300;

/// Load a `TSigner` from a base64-encoded secret file.
///
/// The file is expected to contain a single base64-encoded HMAC secret
/// (with or without trailing newline), as generated by `tsig-keygen`.
pub(crate) async fn load_tsigner_from_file(
    key_name: &str,
    path: &str,
    algorithm: TsigAlgorithm,
    fudge: u16,
) -> Result<TSigner> {
    let content = tokio::fs::read_to_string(path)
        .await
        .with_context(|| format!("reading TSIG key file: {path}"))?;
    let secret = BASE64
        .decode(content.trim())
        .context("decoding TSIG secret from base64")?;
    let name =
        Name::from_ascii(key_name).with_context(|| format!("invalid TSIG key name: {key_name}"))?;
    TSigner::new(secret, algorithm, name, fudge)
        .map_err(|e| anyhow::anyhow!("creating TSigner: {e}"))
}
